name: Build Backend Docker Image and Push it to ECR
on:
  push:
    # branches: [ main ]
    paths:
    - 'backend/**'
env:
  ASSUME_ROLE_NAME: poc-github-actions-assume-role
  ACC_NO: ${{ secrets.ACC_NO }}
  REGION: ${{ secrets.REGION }}
  BACKEND_REPO_NAME: ${{ secrets.BACKEND_REPO_NAME }}
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set Git user
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Get the Git tag and the commit
      run: echo "GITTAG=$(git describe --tags)" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Backend Docker Build and Tag
      run: |
        docker build -t backend:latest .
        echo $GITTAG
        docker tag backend:latest "${{ env.ACC_NO }}.dkr.ecr.${{ env.REGION }}.amazonaws.com/${{ env.BACKEND_REPO_NAME }}:$GITTAG"
      working-directory: ./backend

    - name: Install Bandit
      run: pip install bandit

    - name: Bandit Scan
      run: bandit -r ./backend -f html -o bandit-report.html
      continue-on-error: true

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Frontend Docker Image Scan Report
        path: bandit-report.html

    - name: Setup AWScli
      uses: unfor19/install-aws-cli-action@v1

    - name: Authenticate To AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ env.REGION }}
        role-to-assume: ${{ env.ASSUME_ROLE_NAME }}
        role-session-name: GitHub Federation  

    - name: Login to ECR
      run: aws ecr get-login-password --region ${{ env.REGION }} | docker login --username AWS --password-stdin ${{ env.ACC_NO }}.dkr.ecr.${{ env.REGION }}.amazonaws.com

    - name: Push Docker image
      run: docker push "${{ env.ACC_NO }}.dkr.ecr.${{ env.REGION }}.amazonaws.com/${{ env.BACKEND_REPO_NAME }}:$GITTAG"
