name: Build Frontend Docker Image and Push it to ECR
on:
  push:
    # branches: [ main ]
    paths:
    - 'frontend/**'
env:
  ASSUME_ROLE_ARN: ${{ secrets.ASSUME_ROLE_ARN }}
  ACC_NO: ${{ secrets.ACC_NO }}
  REGION: ${{ secrets.REGION }}
  FRONTEND_REPO_NAME: ${{ secrets.FRONTEND_REPO_NAME }}

jobs:
  docker-build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Check out code
      uses: actions/checkout@v4
      with: 
        fetch-depth: 0 


    - name: Set Git user
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Get the Git tag and the commit
      run: | 
        GITTAG=$(git describe --tags)
        echo "GITTAG=${GITTAG}" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Frontend Docker Build and Tag
      run: |
        docker build -t frontend .
        docker tag backend ${{ env.ACC_NO }}.dkr.ecr.${{ env.REGION }}.amazonaws.com/${{ env.FRONTEND_REPO_NAME }}:${{ env.GITTAG }}
      working-directory: ./frontend

    - name: Install Bandit
      run: pip install bandit

    - name: Bandit Scan
      run: bandit -r ./frontend -f html -o bandit-report.html
      continue-on-error: true

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Frontend Docker Image Scan Report
        path: bandit-report.html

    - name: Setup AWScli
      uses: unfor19/install-aws-cli-action@v1

    - name: Authenticate To AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ env.REGION }}
        role-to-assume: ${{ env.ASSUME_ROLE_ARN }}
        role-session-name: GitHubFederation

    - name: Login to ECR
      run: aws ecr get-login-password --region ${{ env.REGION }} | docker login --username AWS --password-stdin ${{ env.ACC_NO }}.dkr.ecr.${{ env.REGION }}.amazonaws.com

    - name: Push Docker image
      run: docker push ${{ env.ACC_NO }}.dkr.ecr.${{ env.REGION }}.amazonaws.com/${{ env.FRONTEND_REPO_NAME }}:${{ env.GITTAG }}
